#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Command-Tdump
version:      1
version_from: lib/Devel/Command/Tdump.pm
installdirs:  site
requires:
    Devel::Command:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
